# Uncomment the next line to define a global platform for your project

  platform :ios, '10.0'

def thirdLibs
  # third libs
  pod 'Protobuf', '3.17.0'
  pod "CocoaLumberjack", '3.6.1'
  pod 'AliyunOSSiOS', '2.10.8'
  pod 'Armin', '1.1.0'
  pod 'SSZipArchive', '2.4.2'
  pod 'SwifterSwift', '5.2.0'
  pod 'Masonry', '1.1.0'
  pod 'SDWebImage', '5.12.0'

  # agora libs
  pod 'AgoraRtcEngine_iOS/RtcBasic', '3.6.2'
  pod 'AgoraRtm_iOS', '1.4.8'
end

target 'AgoraBuilder' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  thirdLibs
  
  # open source libs
  pod 'AgoraProctorSDK/Build', :path => '../../AgoraProctorSDK_Local.podspec'
  pod 'AgoraProctorUI/Binary', :path => '../../AgoraProctorUI_Local.podspec'
  
  # common libs
  pod 'AgoraWidget/Binary', :path => '../../../apaas-common-libs-ios/AgoraWidget_Local.podspec'
  pod 'AgoraUIBaseViews/Binary', :path => '../../../apaas-common-libs-ios/AgoraUIBaseViews_Local.podspec'

  # close libs
  pod 'AgoraEduCore/Binary', :path => '../../../cloudclass-ios/AgoraEduCore_Local.podspec'

  post_install do |installer|
     installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
          config.build_settings['BITCODE_GENERATION_MODE'] = 'bitcode'
          config.build_settings['ENABLE_BITCODE'] = 'YES'
        end
     end
  end
end
